basefolder.name = target/ExtentReport
basefolder.datetimepattern=dd-MMM-YY HH-mm-ss
extent.reporter.spark.start=true
extent.reporter.spark.out=report.html
screenshot.dir=screenshots
screenshot.rel.path=./screenshots/